src/main.cpp

@doanac this is enough to get aktualizr at least connecting to the OTA Server on my machine with a suitably configured softhsm. (I'm seeing a "could not put manifest" error though that I think might have to do with an Uptane key).
You can see the FIXME comments in the PR for where I just hack through things. What I think we ought to do to fix them is support an "overrides" parameter in the ota_api's /devices/ POST.
The value of "overrides" would be a dict, mapping keys which are `sota_toml_section.key` to values which are the corresponding values.
So for example:
```
overrides = {
'storage.path': '"/var/not-sota"',
'tls.ca_source': '"pkcs11"',
}
```
Would result in a sota.toml with those overrides applied to the default, like so:
```
[storage]
path = "/var/not-sota"
...
[tls]
ca_source = …
```

TLS using a hardware security module

---

src/main.cpp

Whoops. Tested both ways on LMP 533.

main.cpp: fix regression for non-HSM based provisioning

---

src/main.cpp

Use the base functions used by base64_encode in order to be compatible
with boost 1.69 and 1.71, as base64_encode was removed from boost 1.71.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

Drop base64_encode, removed in boost 1.71

---

CMakeLists.txt
src/main.cpp

We already know the value of the platform when this is built. OE
has it defined as "MACHINE", so this can just be set at build time
to eliminate the need to provide this value.
Signed-off-by: Andy Doan <andy@foundries.io>

Fix probing of hwid

---

CMakeLists.txt
src/main.cpp

If users are building factories with tags defined, its reasonable to
assume that this resulting lmp-device-register should default to
subscribing to targets with the this same tag.
Signed-off-by: Andy Doan <andy@foundries.io>

Supply a default tag if found

---

src/main.cpp

This does three things we've been talking about with regards to usability:
* The command no longer requires "-n <name>". It will default to the UUID
* It won't corrupt an existing sql.db if its detected
* Adding a "--force" flag.

Usability improvements

---

src/main.cpp

This makes testing a lot easier
Signed-off-by: Andy Doan <andy@foundries.io>

Allow device api to be overridden at runtime

---

src/main.cpp

lmp-device-register drives/defines whether to turn on the ostreeproxy
usage to make sure that it's enabled only for the LmP/platform that
includes the aklite version capable to infer/derive Docker Regiistry an auth cred
endpoint from a URL to an ostreeproxy server.
Signed-off-by: Mike Sul <mike.sul@foundries.io>

Add parameter to turn on an ostree proxy usage

---

src/main.cpp

In order to generalize the API hit by the `lmp-device-register` command, I've added a `-H`/`--api-token-header` CLI option that allows users to specify the exact authorization header they need.
I'd expect the command to be called something like:
```sh
./lmp-device-register -f ${FACTORY} -T ${JWT_TOKEN} -H Authorization -r https://${API_GATEWAY}/sign -n ${DEVICE_NAME}
```
The specific use case is ensuring that we can use a general-purpose `Authorization` header for a [AWS Cognito-based authorizer](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-invoke-api-integrated-with-cognito-user-pool.html). 
* Seemed out of scope to generalize and provide variadic header arguments
* I kept the `OSF-TOKEN` as a default header to not have breaking changes
* Haven't compiled and …

Add an api-token-header argument

---

CMakeLists.txt
src/main.cpp

meta-updater code in OE allows the actual ota client to be configurable
via the SOTA_CLIENT setting. This change removes our hard coded
dependency on aktualizr-lite so that it can be used with any proper
SOTA_CLIENT.
Signed-off-by: Andy Doan <andy@foundries.io>

Remove hard-coded usage of aktualizr-lite

---

src/main.cpp

Path used for loading the pkcs11 engine is different when built with
OpenSSL 3 (default in LmP kirkstone).
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

main: use engines from openssl 3 by default

---

src/main.cpp

Change the criterion of a registered device.
If both the DB and the device cert are present, then a device is considered registered.
Signed-off-by: Mike <mike.sul@foundries.io>

Extend the check whether a device is registered.

---

CMakeLists.txt
src/main.cpp

The way we write out config files isn't completely safe. There are a couple of problems:
1) sota.toml can get written before other files like pkey.pem If the device reboots, it might come up and *think* it's registered but not actually have everything it needs.
2) We don't write files safely to disk
This could result in something like a zero-byte sota.toml.
This change introduces a safe way to write files. The same technique is used in Fioconfig where you:
* write to a temp file
* fsync this to disk
* rename the file to the actual file
This sequence is power fail safe.
Additionally, we only write sota.toml to disk after we've written everything else.

Make writing of config files more safe

---

CMakeLists.txt
clang-tidy.sh
src/main.cpp

Default tag can be read from the filesystem at runtime. When it's not possible to retreive from the files, lmp-device-register will prompt user for input.
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@foundries.io>

Remove DEFAULT_TAG, AKLITE_TAGS and DEVICE_FACTORY

---

src/main.cpp

End sentences with periods where needed and don't print default values as boost already does this.

Cleanup the usage message

---

CMakeLists.txt
inc/curl.hpp
inc/device_register.h
src/auth.cpp
src/main.cpp
src/openssl.cpp
src/options.cpp
src/pkcs11.cpp
src/pkcs11_stub.cpp

Uses libp11 and the openssl API instead of the helper programs to access pkcs#11 and openssl.
Needs one fix to libp11 (for token initialization) and one missing feature (EC key generation, proposed upstream) plus a fix required to support TPM.
Co-developed-by: Milosz Wasilewski <milosz.wasilewski@foundries.io>

main: refactor lmp-device-register

---

src/options.cpp

Check that a valid UUID was provided. This avoid a later error when contacting the server.

options: validate the UUID input parameter

---

src/options.cpp

Fix compilation issue.
Fixes 3c871e7("options: validate the UUID input parameter")
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

options: fix regression on UUID validation

---

inc/device_register.h
src/options.cpp

Some legacy products might have been registered with an invalid UUID. Allow them to continue registering by ignoring the UUID validation step.

options: toggle UUID validation

---

inc/curl.hpp
inc/device_register.h
src/auth.cpp
src/main.cpp
src/openssl.cpp
src/options.cpp
src/pkcs11.cpp
src/pkcs11_stub.cpp

The current implementation allows multiple key pairs to be stored in the HSM using the same "tls" label, which leads to certificate errors inside aklite. Even a previous incomplete lmp-device-register execution might leave these keys behind.
This commit makes sure there are no other stored keys using the same label before creating a new key pair during the registration process.

pkcs11: remove existing PKCS#11 keys to avoid label conflicts

---

src/auth.cpp

This was originally fixed in:
ccd4499 (Print log message of each error, 2022-11-21)
But there was a regression in:
263d11e (main: refactor lmp-device-register, 2023-04-11)

auth: Fix dump of http error replies when an 'error' field is used
